export const PUBLIC_CONTENT_SEED = {
  languages: [
    { code: 'EN', label: 'English' },
    { code: 'AR', label: 'Arabic' },
    { code: 'UR', label: 'Urdu' },
    { code: 'FR', label: 'French' },
    { code: 'DE', label: 'German' },
    { code: 'ES', label: 'Spanish' },
    { code: 'ZH', label: 'Chinese' },
    { code: 'JA', label: 'Japanese' },
    { code: 'KO', label: 'Korean' },
    { code: 'PT', label: 'Portuguese' },
    { code: 'RU', label: 'Russian' },
    { code: 'HI', label: 'Hindi' },
    { code: 'TR', label: 'Turkish' },
    { code: 'IT', label: 'Italian' },
    { code: 'NL', label: 'Dutch' },
  ],
  homePage: {
    stats: [
      { value: '525+', label: 'AI Models' },
      { value: '82K', label: 'Builders' },
      { value: '28', label: 'AI Labs' },
      { value: '4.8', label: 'Avg Rating' },
    ],
    hero: {
      eyebrow: '347 models live - updated daily',
      title: 'Find your perfect',
      accent: 'AI model',
      subtitle: 'with guided discovery',
      description:
        "You don't need to know anything about AI to get started. Just click the box below - we'll do the rest together.",
      placeholder: 'Click here and type anything - or just say hi!',
      cta: "Let's go",
    },
    featuredModelIds: ['gpt5', 'claude-opus46', 'claude-sonnet46', 'gemini25-pro', 'llama4-maverick', 'deepseek-v3'],
    heroActions: [
      { icon: '🎨', label: 'Create image', prompt: 'Create an image for me' },
      { icon: '🎵', label: 'Generate audio', prompt: 'Generate audio for me' },
      { icon: '🎬', label: 'Create video', prompt: 'Create a video for me' },
      { icon: '📊', label: 'Create slides', prompt: 'Create a presentation or slides for me' },
      { icon: '📈', label: 'Create infographics', prompt: 'Create an infographic for me' },
      { icon: '❓', label: 'Create quiz', prompt: 'Create a quiz for me' },
      { icon: '🗂️', label: 'Create flashcards', prompt: 'Create flashcards for me' },
      { icon: '🧠', label: 'Create mind map', prompt: 'Create a mind map for me' },
      { icon: '📉', label: 'Analyze data', prompt: 'Help me analyze data' },
      { icon: '✍️', label: 'Write content', prompt: 'Help me write content' },
      { icon: '💻', label: 'Code generation', prompt: 'Help me with code generation and debugging' },
      { icon: '📄', label: 'Document analysis', prompt: 'Help me analyze documents and extract key information' },
      { icon: '🌐', label: 'Translate', prompt: 'Help me translate text to another language' },
      { icon: '🔭', label: 'Just exploring', prompt: 'I am just exploring what AI can do' },
    ],
    builderFeatures: [
      {
        icon: '🧭',
        title: 'Guided Discovery Chat',
        description:
          "I'll greet you, ask about your goals, and have a genuine conversation before recommending models. No overwhelming lists.",
        href: '/chat',
      },
      {
        icon: '📐',
        title: 'Prompt Engineering Guide',
        description:
          'Every model includes tailored prompt templates, principles, and examples so you get the best output from day one.',
        href: '/marketplace',
      },
      {
        icon: '🤖',
        title: 'Agent Builder',
        description:
          'Step-by-step agent creation guides for every model - system prompts, tool configuration, memory setup, deployment.',
        href: '/agents',
      },
      {
        icon: '💰',
        title: 'Flexible Pricing',
        description:
          'Free tiers, pay-per-use, subscriptions, and enterprise plans. Transparent pricing with no hidden fees.',
        href: '/marketplace',
      },
      {
        icon: '⭐',
        title: 'User Reviews & Ratings',
        description:
          'Verified reviews from real builders, benchmark scores, and detailed I/O specs to help you choose confidently.',
        href: '/marketplace',
      },
      {
        icon: '🔬',
        title: 'Research Feed',
        description:
          'Daily curated AI research, model releases, and breakthroughs from top labs - stay ahead of the curve.',
        href: '/discover',
      },
    ],
    labs: [
      { icon: '🧠', name: 'OpenAI', summary: '3 models · GPT-5.4, Sora 2', href: '/marketplace' },
      { icon: '⚡', name: 'Anthropic', summary: '3 models · Opus, Sonnet, Haiku', href: '/marketplace' },
      { icon: '🔬', name: 'Google DeepMind', summary: '5 models · Gemini 3.1, Veo 3', href: '/marketplace' },
      { icon: '𝕏', name: 'xAI (Grok)', summary: '2 models · Grok-4-1, Grok-Imagine', href: '/marketplace' },
      { icon: '💻', name: 'DeepSeek', summary: '3 models · V3, V3.2, R1', href: '/marketplace' },
      { icon: '🦙', name: 'Meta (Llama)', summary: '2 models · Maverick, Scout', href: '/marketplace' },
      { icon: '🀄', name: 'Alibaba (Qwen)', summary: '2 models · Qwen3-Max, Coder', href: '/marketplace' },
      { icon: '🌀', name: 'Mistral', summary: '2 models · Devstral 2, Medium 3.1', href: '/marketplace' },
      { icon: '🟢', name: 'NVIDIA NIM', summary: '4 models · Nemotron Ultra, Nano', href: '/marketplace' },
      { icon: '🔷', name: 'GLM (Zhipu)', summary: '3 models · GLM-5, 4.7, 4.6V', href: '/marketplace' },
      { icon: '🌙', name: 'Moonshot (Kimi)', summary: '2 models · K2.5, K2-Thinking', href: '/marketplace' },
    ],
    comparisonRows: [
      {
        model: 'GPT-5.4',
        lab: 'OpenAI',
        context: '1.05M',
        inputPrice: '$2.50',
        outputPrice: '$15',
        multimodal: true,
        speed: 'Fast',
        speedTone: 'teal',
        bestFor: 'High-precision professional tasks',
      },
      {
        model: 'Claude Opus 4.6',
        lab: 'Anthropic',
        context: '200K/1M β',
        inputPrice: '$5',
        outputPrice: '$25',
        multimodal: true,
        speed: 'Moderate',
        speedTone: 'amber',
        bestFor: 'Agents, advanced coding',
      },
      {
        model: 'Claude Sonnet 4.6',
        lab: 'Anthropic',
        context: '200K/1M β',
        inputPrice: '$3',
        outputPrice: '$15',
        multimodal: true,
        speed: 'Fast',
        speedTone: 'teal',
        bestFor: 'Code, data, content at scale',
      },
      {
        model: 'Claude Haiku 4.5',
        lab: 'Anthropic',
        context: '200K',
        inputPrice: '$1',
        outputPrice: '$5',
        multimodal: true,
        speed: 'Fastest',
        speedTone: 'accent',
        bestFor: 'Real-time, high-volume',
      },
      {
        model: 'Gemini 3.1 Pro',
        lab: 'Google',
        context: '2M-5M',
        inputPrice: '$2',
        outputPrice: '$12',
        multimodal: true,
        speed: 'Moderate',
        speedTone: 'amber',
        bestFor: 'Deep reasoning, long context',
      },
      {
        model: 'Gemini 3 Flash',
        lab: 'Google',
        context: '1M',
        inputPrice: '$2',
        outputPrice: '$12',
        multimodal: true,
        speed: 'Moderate',
        speedTone: 'amber',
        bestFor: 'High-volume chat & coding',
      },
      {
        model: 'Gemini 3.1 Flash-Lite',
        lab: 'Google',
        context: '1M',
        inputPrice: '$0.10',
        outputPrice: '$0.40',
        multimodal: true,
        speed: 'Fastest',
        speedTone: 'accent',
        bestFor: 'Low-cost agents, translation',
      },
      {
        model: 'Grok-4-1 Fast',
        lab: 'xAI',
        context: '2000K',
        inputPrice: '$0.20',
        outputPrice: '$0.50',
        multimodal: true,
        speed: 'Moderate',
        speedTone: 'amber',
        bestFor: 'Real-time X data analysis',
      },
      {
        model: 'DeepSeek-V3',
        lab: 'DeepSeek',
        context: '128K',
        inputPrice: '~$0.07',
        outputPrice: '~$0.28',
        multimodal: true,
        speed: 'Moderate',
        speedTone: 'amber',
        bestFor: 'Budget general model',
      },
      {
        model: 'Llama 4 Maverick',
        lab: 'Meta',
        context: '128K',
        inputPrice: 'Free',
        outputPrice: 'Free',
        multimodal: true,
        speed: 'Moderate',
        speedTone: 'amber',
        bestFor: 'Open-source multimodal',
      },
      {
        model: 'Qwen3-Max',
        lab: 'Alibaba',
        context: '128K',
        inputPrice: '$0.40',
        outputPrice: '$1.20',
        multimodal: true,
        speed: 'Moderate',
        speedTone: 'amber',
        bestFor: 'Multilingual / APAC',
      },
      {
        model: 'Nemotron Ultra 253B',
        lab: 'NVIDIA',
        context: '131K',
        inputPrice: '$0.60',
        outputPrice: '$1.80',
        multimodal: false,
        speed: 'Moderate',
        speedTone: 'amber',
        bestFor: 'Enterprise reasoning & RAG',
      },
      {
        model: 'kimi-k2.5',
        lab: 'Moonshot',
        context: '262K',
        inputPrice: '$0.60',
        outputPrice: '$3',
        multimodal: true,
        speed: 'Fastest',
        speedTone: 'accent',
        bestFor: 'Multi-agent RAG, visual coding',
      },
    ],
    trending: [
      {
        badge: 'Just Released',
        badgeTone: 'teal',
        lab: 'Anthropic',
        title: 'Claude Opus 4.6 & Sonnet 4.6',
        description:
          'Adaptive Thinking and 1M token context mark a major leap in agent capability. Now the most intelligent Claude for coding and agentic tasks.',
        prompt: 'Tell me about Claude Opus 4.6 and Sonnet 4.6',
      },
      {
        badge: 'Hot',
        badgeTone: 'amber',
        lab: 'Google DeepMind',
        title: 'Gemini 3.1 Pro - Thought Signatures',
        description:
          'Thought Signatures bring new transparency to deep reasoning. 5M context window makes it the go-to for ultra-long document analysis.',
        prompt: 'Explain Gemini 3.1 Pro Thought Signatures',
      },
      {
        badge: 'Computer Use',
        badgeTone: 'blue',
        lab: 'OpenAI',
        title: 'GPT-5.4 - Native Computer-Use Agents',
        description:
          'GPT-5.4 introduces native computer-use agents, letting it operate browsers, apps, and files autonomously with improved reasoning efficiency.',
        prompt: 'What are GPT-5.4 native computer-use agents?',
      },
      {
        badge: 'Real-Time',
        badgeTone: 'rose',
        lab: 'xAI',
        title: 'Grok-4-1 Fast - 4-Agent Architecture',
        description:
          'Grok 4-agent architecture with real-time X data access and 2M context makes it unique for real-time analysis tasks.',
        prompt: 'Explain Grok-4-1 Fast 4-agent architecture',
      },
      {
        badge: 'Open Source',
        badgeTone: 'blue',
        lab: 'Meta',
        title: 'Llama 4 Maverick - 400B MoE',
        description:
          "Meta's 400B Mixture-of-Experts model with native multimodal understanding. Free to self-host with a full commercial license.",
        prompt: 'Tell me about Llama 4 Maverick 400B MoE',
      },
      {
        badge: 'Coding',
        badgeTone: 'teal',
        lab: 'Mistral',
        title: 'Devstral 2 - Fastest Coding Agent',
        description:
          "Mistral's coding agent with 256K context, multi-file edits, and codebase navigation. The fastest software engineering model available.",
        prompt: 'Tell me about Devstral 2',
      },
    ],
    budgetBuckets: [
      {
        icon: '🆓',
        tone: 'teal',
        title: 'Free & Open Source',
        description: 'Llama 4 Maverick, Llama 4 Scout, DeepSeek-V3, DeepSeek-R1 - self-host with zero API cost.',
        cta: '6 models available',
        href: '/marketplace',
      },
      {
        icon: '💸',
        tone: 'blue',
        title: 'Budget - Under $0.50/1M',
        description: 'Gemini 3.1 Flash-Lite, Mistral Medium, Nemotron Nano - best performance per dollar.',
        cta: '9 models available',
        href: '/marketplace',
      },
      {
        icon: '⚖️',
        tone: 'amber',
        title: 'Mid-Range - $1-$5/1M',
        description: 'Claude Sonnet 4.6, Claude Haiku 4.5, Gemini 3.1 Pro, GPT-5.4, Qwen3-Max.',
        cta: '11 models available',
        href: '/marketplace',
      },
      {
        icon: '🏆',
        tone: 'accent',
        title: 'Premium - $5+/1M',
        description: 'Claude Opus 4.6, Sora 2 Pro, gpt-image-1.5 - top-tier quality for demanding workloads.',
        cta: '5 models available',
        href: '/marketplace',
      },
    ],
    useCases: [
      {
        icon: '💻',
        title: 'Code Generation',
        models: 'Claude Opus 4.6, Devstral 2, GPT-5.4, Qwen3-Coder',
        cta: 'Start building',
        prompt: 'I need help with code generation and debugging',
      },
      {
        icon: '🎨',
        title: 'Image Generation',
        models: 'gpt-image-1.5, Grok-Imagine-Pro, Gemini Flash Image',
        cta: 'Create images',
        prompt: 'I want to generate realistic images for marketing',
      },
      {
        icon: '🤖',
        title: 'AI Agents',
        models: 'GPT-5.4, Claude Opus 4.6, kimi-k2.5, Grok-4-1',
        cta: 'Build agents',
        prompt: 'I need to create AI agents for workflow automation',
      },
      {
        icon: '📄',
        title: 'Document Analysis',
        models: 'Claude Sonnet 4.6, Gemini 3.1 Pro, Nemotron Ultra',
        cta: 'Analyze docs',
        prompt: 'I need to analyze documents and extract key information',
      },
      {
        icon: '🎬',
        title: 'Video Generation',
        models: 'Sora 2 Pro, Veo 3.1, Grok-Imagine-Video',
        cta: 'Create video',
        prompt: 'I want to create professional video content',
      },
      {
        icon: '🔊',
        title: 'Voice & Audio',
        models: 'Gemini-TTS, ElevenLabs, Whisper v3',
        cta: 'Add voice',
        prompt: 'I want to add voice and speech recognition to my app',
      },
      {
        icon: '🌍',
        title: 'Multilingual / Translation',
        models: 'Qwen3-Max (119 langs), Gemini 3.1 Flash-Lite, GLM-4.7',
        cta: 'Go multilingual',
        prompt: 'I need multilingual AI for global markets',
      },
      {
        icon: '🔢',
        title: 'Math & Research',
        models: 'DeepSeek-R1, QwQ-32B, Gemini 3.1 Pro',
        cta: 'Start researching',
        prompt: 'I need advanced math and reasoning models for research',
      },
    ],
    newsletter: {
      eyebrow: 'Stay ahead of the curve',
      title: 'New models drop every week.',
      subtitle: "Don't miss a release.",
      description:
        'Get a curated weekly digest: new model releases, benchmark comparisons, pricing changes, and prompt engineering tips - straight to your inbox.',
      placeholder: 'your@email.com',
      buttonLabel: 'Subscribe free',
      finePrint: 'No spam. Unsubscribe any time. Trusted by 82K+ builders.',
    },
    footer: {
      brand: 'NexusAI Model Marketplace',
      links: [
        { label: 'Models', href: '/marketplace' },
        { label: 'Research', href: '/discover' },
        { label: 'API', href: '#' },
        { label: 'Privacy', href: '#' },
        { label: 'Terms', href: '#' },
      ],
    },
  },
  chatPanel: {
    tabs: [
      { key: 'use_cases', label: 'Use Cases' },
      { key: 'create', label: 'Create' },
      { key: 'analyze', label: 'Analyze' },
      { key: 'prototype', label: 'Prototype' },
      { key: 'business', label: 'Business' },
      { key: 'monitor', label: 'Monitor' },
      { key: 'learn', label: 'Learn' },
    ],
    prompts: {
      use_cases: [
        'Help me find the best AI model for my project',
        'I want to build an AI chatbot for my website',
        'Generate realistic images for my marketing campaign',
        'Analyze documents and extract key information',
        'Create AI agents for workflow automation',
        'Add voice and speech recognition to my app',
      ],
      monitor: [
        'Track regulatory changes in my industry',
        'Alert me when a product drops in price',
        'Track my portfolio and alert me on big moves',
        'Watch for job postings at target companies',
        'Monitor a competitor daily for any changes',
        'Set up news alerts for my niche topic',
      ],
      prototype: [
        'Build a quick prototype for my app idea',
        'Create a REST API scaffold for my project',
        'Generate a landing page from my description',
        'Turn my wireframe description into working HTML',
        'Build a chatbot prototype in under 10 minutes',
        'Create a data pipeline prototype with sample code',
      ],
      business: [
        'Write a business plan for my startup idea',
        'Create a go-to-market strategy for my product',
        'Draft a financial projection model for investors',
        'Identify my target market and ideal customer profile',
        'Write an executive summary for my pitch deck',
        'Create a competitive analysis for my industry',
      ],
      create: [
        'Write a blog post about AI trends in my industry',
        'Create social media captions for my product launch',
        'Generate an email newsletter for my audience',
        'Write a product description that converts',
        'Create an infographic script on a complex topic',
        'Draft a script for a 2-minute explainer video',
      ],
      analyze: [
        'Analyze this dataset and summarize key insights',
        'Compare the top AI models by performance and cost',
        'Research the competitive landscape in my market',
        'Summarize recent AI research papers on a topic',
        'Identify trends from my customer feedback data',
        'Build a pros and cons comparison for two options',
      ],
      learn: [
        'Explain how large language models work simply',
        'Teach me prompt engineering from scratch',
        'What is RAG and when should you use it?',
        'Help me understand AI agent architectures',
        'Explain the difference between fine-tuning and RAG',
        'Give me a 5-minute overview of AI safety concepts',
      ],
    },
    quickActions: [
      {
        group: 'Navigation & Tools',
        items: ['Go to Marketplace', 'Browse Agents', 'Discover New Models', 'Open Dashboard'],
      },
      {
        group: 'Create & Generate',
        items: ['Write a blog post', 'Generate code snippet', 'Create a template', 'Draft an email'],
      },
      {
        group: 'Analyze & Write',
        items: ['Summarize this', 'Explain step by step', 'Compare options', 'Review and improve'],
      },
    ],
  },
  marketplaceTypeChips: [
    { key: 'all', label: 'All' },
    { key: 'language', label: 'Language' },
    { key: 'vision', label: 'Vision' },
    { key: 'code', label: 'Code' },
    { key: 'image', label: 'Image Gen' },
    { key: 'audio', label: 'Audio' },
    { key: 'video', label: 'Video' },
    { key: 'open', label: 'Open Source' },
  ],
  discoverCategories: ['All', 'Language', 'Vision', 'Code', 'Reasoning', 'Multimodal', 'Audio', 'Video', 'Open Source'],
  agentTemplates: [
    {
      id: 'customer-support',
      icon: '💬',
      name: 'Customer Support Bot',
      desc: 'Handles inquiries, escalations, and ticket creation. Integrates with helpdesk tools.',
      tags: ['Support', 'Chat', 'Automation'],
      popular: true,
    },
    {
      id: 'research-agent',
      icon: '🔍',
      name: 'Research Agent',
      desc: 'Deep research with web search, document analysis, and structured reports.',
      tags: ['Research', 'Web Search', 'Reports'],
      popular: true,
    },
    {
      id: 'code-assistant',
      icon: '💻',
      name: 'Code Assistant',
      desc: 'Code generation, review, debugging, and documentation across 50+ languages.',
      tags: ['Code', 'Debug', 'Docs'],
      popular: true,
    },
    {
      id: 'sales-assistant',
      icon: '📈',
      name: 'Sales Assistant',
      desc: 'Lead qualification, follow-ups, CRM updates, and proposal drafting.',
      tags: ['Sales', 'CRM', 'Outreach'],
      popular: false,
    },
    {
      id: 'data-analyst',
      icon: '📊',
      name: 'Data Analyst',
      desc: 'Analyzes datasets, creates visualizations, and generates business insights.',
      tags: ['Data', 'Analytics', 'Insights'],
      popular: false,
    },
    {
      id: 'content-creator',
      icon: '✍️',
      name: 'Content Creator',
      desc: 'Blog posts, social media, email campaigns, and consistent brand voice at scale.',
      tags: ['Content', 'Social', 'SEO'],
      popular: false,
    },
    {
      id: 'hr-assistant',
      icon: '👥',
      name: 'HR Assistant',
      desc: 'Screening, onboarding workflows, policy Q&A, and employee requests.',
      tags: ['HR', 'Recruiting', 'Onboarding'],
      popular: false,
    },
    {
      id: 'finance-agent',
      icon: '💰',
      name: 'Finance Agent',
      desc: 'Invoice processing, expense categorization, and financial reporting.',
      tags: ['Finance', 'Accounting', 'Reports'],
      popular: false,
    },
  ],
  agentWizardSteps: [
    'Choose Template',
    'Select Model',
    'Configure Prompt',
    'Connect Tools',
    'Review & Deploy',
  ],
  billingPlans: [
    {
      name: 'Free',
      price: '$0',
      period: '/mo',
      features: ['50 requests/day', '10 models', 'Community support', '3h guest sessions'],
      current: true,
      cta: 'Current Plan',
    },
    {
      name: 'Pro',
      price: '$19',
      period: '/mo',
      features: ['Unlimited requests', '400+ models', 'Priority support', 'Permanent history', 'API access'],
      current: false,
      cta: 'Upgrade to Pro',
    },
    {
      name: 'Enterprise',
      price: 'Custom',
      period: '',
      features: ['Everything in Pro', 'Custom integrations', 'SLA guarantee', 'Dedicated support', 'SSO & SAML'],
      current: false,
      cta: 'Contact Sales',
    },
  ],
} as const;

export type PublicContentSeed = typeof PUBLIC_CONTENT_SEED;
export type PublicContentKey = keyof PublicContentSeed;
