export const PUBLIC_CONTENT_SEED = {
  languages: [
    { code: 'EN', label: 'English' },
    { code: 'AR', label: 'Arabic' },
    { code: 'UR', label: 'Urdu' },
    { code: 'FR', label: 'French' },
    { code: 'DE', label: 'German' },
    { code: 'ES', label: 'Spanish' },
    { code: 'ZH', label: 'Chinese' },
    { code: 'JA', label: 'Japanese' },
    { code: 'PT', label: 'Portuguese' },
    { code: 'RU', label: 'Russian' },
    { code: 'HI', label: 'Hindi' },
    { code: 'TR', label: 'Turkish' },
  ],
  homeStats: [
    { value: '400+', label: 'AI Models' },
    { value: '50+', label: 'Providers' },
    { value: '10M+', label: 'API Calls' },
    { value: '99.9%', label: 'Uptime' },
  ],
  homeHeroModelIds: ['gpt5', 'claude-opus46', 'gemini25-pro', 'llama4-maverick', 'grok4'],
  chatPanel: {
    tabs: [
      { key: 'use_cases', label: 'Use Cases' },
      { key: 'create', label: 'Create' },
      { key: 'analyze', label: 'Analyze' },
      { key: 'prototype', label: 'Prototype' },
      { key: 'business', label: 'Business' },
      { key: 'monitor', label: 'Monitor' },
      { key: 'learn', label: 'Learn' },
    ],
    prompts: {
      use_cases: [
        'Help me find the best AI model for my project',
        'I want to build an AI chatbot for my website',
        'Generate realistic images for my marketing campaign',
        'Analyse documents and extract key information',
        'Create AI agents for workflow automation',
        'Add voice and speech recognition to my app',
      ],
      monitor: [
        'Track regulatory changes in my industry',
        'Alert me when a product drops in price',
        'Track my portfolio and alert me on big moves',
        'Watch for job postings at target companies',
        'Monitor a competitor daily for any changes',
        'Set up news alerts for my niche topic',
      ],
      prototype: [
        'Build a quick prototype for my app idea',
        'Create a REST API scaffold for my project',
        'Generate a landing page from my description',
        'Turn my wireframe description into working HTML',
        'Build a chatbot prototype in under 10 minutes',
        'Create a data pipeline prototype with sample code',
      ],
      business: [
        'Write a business plan for my startup idea',
        'Create a go-to-market strategy for my product',
        'Draft a financial projection model for investors',
        'Identify my target market and ideal customer profile',
        'Write an executive summary for my pitch deck',
        'Create a competitive analysis for my industry',
      ],
      create: [
        'Write a blog post about AI trends in my industry',
        'Create social media captions for my product launch',
        'Generate an email newsletter for my audience',
        'Write a product description that converts',
        'Create an infographic script on a complex topic',
        'Draft a script for a 2-minute explainer video',
      ],
      analyze: [
        'Analyse this dataset and summarise key insights',
        'Compare the top AI models by performance and cost',
        'Research the competitive landscape in my market',
        'Summarise recent AI research papers on a topic',
        'Identify trends from my customer feedback data',
        'Build a pros and cons comparison for two options',
      ],
      learn: [
        'Explain how large language models work simply',
        'Teach me prompt engineering from scratch',
        'What is RAG and when should you use it?',
        'Help me understand AI agent architectures',
        'Explain the difference between fine-tuning and RAG',
        'Give me a 5-minute overview of AI safety concepts',
      ],
    },
    quickActions: [
      {
        group: 'Navigation & Tools',
        items: ['Go to Marketplace', 'Browse Agents', 'Discover New Models', 'Open Dashboard'],
      },
      {
        group: 'Create & Generate',
        items: ['Write a blog post', 'Generate code snippet', 'Create a template', 'Draft an email'],
      },
      {
        group: 'Analyze & Write',
        items: ['Summarize this', 'Explain step by step', 'Compare options', 'Review and improve'],
      },
    ],
  },
  marketplaceTypeChips: [
    { key: 'all', label: 'All' },
    { key: 'language', label: 'Language' },
    { key: 'vision', label: 'Vision' },
    { key: 'code', label: 'Code' },
    { key: 'image', label: 'Image Gen' },
    { key: 'audio', label: 'Audio' },
    { key: 'video', label: 'Video' },
    { key: 'open', label: 'Open Source' },
  ],
  discoverCategories: ['All', 'Language', 'Vision', 'Code', 'Reasoning', 'Multimodal', 'Audio', 'Video', 'Open Source'],
  agentTemplates: [
    {
      id: 'customer-support',
      icon: '💬',
      name: 'Customer Support Bot',
      desc: 'Handles inquiries, escalations, and ticket creation. Integrates with helpdesk tools.',
      tags: ['Support', 'Chat', 'Automation'],
      popular: true,
    },
    {
      id: 'research-agent',
      icon: '🔍',
      name: 'Research Agent',
      desc: 'Deep research with web search, document analysis, and structured reports.',
      tags: ['Research', 'Web Search', 'Reports'],
      popular: true,
    },
    {
      id: 'code-assistant',
      icon: '💻',
      name: 'Code Assistant',
      desc: 'Code generation, review, debugging, and documentation across 50+ languages.',
      tags: ['Code', 'Debug', 'Docs'],
      popular: true,
    },
    {
      id: 'sales-assistant',
      icon: '📈',
      name: 'Sales Assistant',
      desc: 'Lead qualification, follow-ups, CRM updates, and proposal drafting.',
      tags: ['Sales', 'CRM', 'Outreach'],
      popular: false,
    },
    {
      id: 'data-analyst',
      icon: '📊',
      name: 'Data Analyst',
      desc: 'Analyzes datasets, creates visualizations, and generates business insights.',
      tags: ['Data', 'Analytics', 'Insights'],
      popular: false,
    },
    {
      id: 'content-creator',
      icon: '✍️',
      name: 'Content Creator',
      desc: 'Blog posts, social media, email campaigns, and consistent brand voice at scale.',
      tags: ['Content', 'Social', 'SEO'],
      popular: false,
    },
    {
      id: 'hr-assistant',
      icon: '👥',
      name: 'HR Assistant',
      desc: 'Screening, onboarding workflows, policy Q&A, and employee requests.',
      tags: ['HR', 'Recruiting', 'Onboarding'],
      popular: false,
    },
    {
      id: 'finance-agent',
      icon: '💰',
      name: 'Finance Agent',
      desc: 'Invoice processing, expense categorization, and financial reporting.',
      tags: ['Finance', 'Accounting', 'Reports'],
      popular: false,
    },
  ],
  agentWizardSteps: [
    'Choose Template',
    'Select Model',
    'Configure Prompt',
    'Connect Tools',
    'Review & Deploy',
  ],
  billingPlans: [
    {
      name: 'Free',
      price: '$0',
      period: '/mo',
      features: ['50 requests/day', '10 models', 'Community support', '3h guest sessions'],
      current: true,
      cta: 'Current Plan',
    },
    {
      name: 'Pro',
      price: '$19',
      period: '/mo',
      features: ['Unlimited requests', '400+ models', 'Priority support', 'Permanent history', 'API access'],
      current: false,
      cta: 'Upgrade to Pro',
    },
    {
      name: 'Enterprise',
      price: 'Custom',
      period: '',
      features: ['Everything in Pro', 'Custom integrations', 'SLA guarantee', 'Dedicated support', 'SSO & SAML'],
      current: false,
      cta: 'Contact Sales',
    },
  ],
} as const;

export type PublicContentSeed = typeof PUBLIC_CONTENT_SEED;
export type PublicContentKey = keyof PublicContentSeed;
